import { defineConfig } from 'vite'
import fs from 'fs'
import path from 'path'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

const VALID_LEARNING_CATEGORIES = new Set([
  'Nature',
  'PeopleSociety',
  'PlacesBuildings',
  'ActionsMovements',
  'AbstractConcepts',
  'NumbersTime',
  'ObjectsMaterials',
  'FoodLiving',
  'LanguageCommunication',
  'BodyHealth',
  'Colors',
  'Misc',
])

function figmaAssetResolver() {
  return {
    name: 'figma-asset-resolver',
    resolveId(id) {
      if (id.startsWith('figma:asset/')) {
        const filename = id.replace('figma:asset/', '')
        return path.resolve(__dirname, 'src/assets', filename)
      }
    },
  }
}

function kanjiCategoryWriter() {
  const kanjiFile = path.resolve(__dirname, 'src/app/data/generated/kanji.generated.ts')

  return {
    name: 'kanji-category-writer',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/__tosho-kanji/category', (req, res) => {
        if (req.method !== 'POST') {
          res.statusCode = 405
          res.end('Method not allowed')
          return
        }

        let body = ''
        req.setEncoding('utf8')
        req.on('data', (chunk) => {
          body += chunk
        })
        req.on('end', () => {
          try {
            const payload = JSON.parse(body || '{}') as { kanjiId?: string; learningCategory?: string }
            const { kanjiId, learningCategory } = payload

            if (!kanjiId || !learningCategory || !VALID_LEARNING_CATEGORIES.has(learningCategory)) {
              res.statusCode = 400
              res.end(JSON.stringify({ ok: false, error: 'Invalid kanji id or category' }))
              return
            }

            const source = fs.readFileSync(kanjiFile, 'utf8')
            const match = source.match(/export const KANJI: KanjiEntry\[\] = (\[[\s\S]*\]);/)
            if (!match) {
              res.statusCode = 500
              res.end(JSON.stringify({ ok: false, error: 'Could not locate generated KANJI export' }))
              return
            }

            const entries = JSON.parse(match[1]) as Array<{ id: string; learningCategory?: string }>
            const entry = entries.find((item) => item.id === kanjiId)
            if (!entry) {
              res.statusCode = 404
              res.end(JSON.stringify({ ok: false, error: 'Kanji not found' }))
              return
            }

            entry.learningCategory = learningCategory
            const output = `import type { KanjiEntry } from "../../types";

// Generated by scripts/build-kanji-data.py from KANJIDIC2, JMdict_e, and KRADFILE.
// Do not hand-edit this file; update the generator or source data instead.

export const KANJI: KanjiEntry[] = ${JSON.stringify(entries, null, 2)};
`

            fs.writeFileSync(kanjiFile, output, 'utf8')
            res.setHeader('Content-Type', 'application/json')
            res.end(JSON.stringify({ ok: true, kanjiId, learningCategory }))
          } catch (error) {
            res.statusCode = 500
            res.end(JSON.stringify({ ok: false, error: error instanceof Error ? error.message : 'Unknown error' }))
          }
        })
      })
    },
  }
}

export default defineConfig({
  plugins: [
    figmaAssetResolver(),
    kanjiCategoryWriter(),
    // The React and Tailwind plugins are both required for Make, even if
    // Tailwind is not being actively used - do not remove them.
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      manifest: {
        name: 'ToshoKanji',
        short_name: 'ToshoKanji',
        description: 'Collect kanji and radicals through a gacha-inspired Japanese learning app.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#050411',
        theme_color: '#ff3d71',
        icons: [
          {
            src: '/icons/toshokanji-icon.svg',
            sizes: 'any',
            type: 'image/svg+xml',
            purpose: 'any',
          },
          {
            src: '/icons/toshokanji-icon-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: '/icons/toshokanji-icon-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: '/icons/toshokanji-maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        cleanupOutdatedCaches: true,
        navigateFallback: '/index.html',
        globPatterns: ['**/*.{js,css,html,ico}'],
        maximumFileSizeToCacheInBytes: 25 * 1024 * 1024,
      },
      devOptions: {
        enabled: false,
      },
    }),
  ],
  resolve: {
    alias: {
      // Alias @ to the src directory.
      '@': path.resolve(__dirname, './src'),
    },
  },

  // File types to support raw imports. Never add .css, .tsx, or .ts files to this.
  assetsInclude: ['**/*.svg', '**/*.csv'],
})
